PROJETFINAL/urls.py
import forum.urls
from sentimentanalysis.views import *
import mon_chatbot.urls
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from accounts.views import *
from mon_chatbot.views import *
from quizes.views import *
from GlobalApp.views import *

from django.views.static import serve
from django.conf.urls.static import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('',include('accounts.urls',namespace='accounts')),
    path('', include(forum.urls), name='forum'),
    path('', include(mon_chatbot.urls), name='chatbot'),
    path('quize/', QuizListView.as_view(), name='main-view'),
    path('quize/<pk>/', quiz_view, name='quiz-view'),
    path('quize/<pk>/save/', save_quiz_view, name='save-view'),
    path('quize/<pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('analyser/<id>',AnalyseData, name = 'AnalyseData'),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from .views import *
app_name = 'accounts'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('profil/', profile_view, name='profile'),
    path('info/<id>',my_info, name='my_info'),
    path('amis/<id>',amis, name='amis'),
    path('experts/<id>',experts, name='experts'),
    path('groupes/<id>',groupes, name='groupes'),
]

forum/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('forum/<int:id>', forum_page_groupe, name='forum_g'),
    path('forum/<slug:usrname>', forum_page_amis, name='forum_a'),
    path('forum/', forum_page, name='forum'),
    path('forum/<int:id>/<int:pk>', poste_pub, name='forum_p'),
    path('forum/<slug:usrname>/<int:id>', env_message, name='forum_m'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profiles_imgs')

    def __str__(self):
        return self.user.username + ' Profile'

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

forum/forms.py
from django import forms


class messageForm(forms.Form):
    message = forms.CharField(max_length=10000)

class PostForm(forms.Form):
    title = forms.CharField(max_length=100)
    body = forms.CharField(max_length=10000)

accounts/views.py
from django import utils
from forum.models import *
from GlobalApp.models import *
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import RegisterForm
from django.contrib.auth.models import Group
from django.contrib.admin.views.decorators import staff_member_required
from accounts.models import Profile
from django.views.decorators.csrf import csrf_protect

# Create your views here.


def home(request):

    return render(request, 'index.html')


@staff_member_required
def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            # à changer ==> patient . create()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='Patients')
            user.groups.add(group)

            return redirect('login')
    return render(request, 'register.html', {'form': form})


@csrf_protect
def login(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login_user(request, user)
                return redirect('home')
            else:
                return render(request, 'account.html')

    return render(request, 'login.html')


def logoutUser(request):
    logout(request)
    # return redirect('login')
    return redirect('home')


def profile_view(request):
    pats = Patient.objects.all()
    list = []
    for pat in pats:
        list.append(pat.user)
    if request.user in list :        
        context = {
            'profiles' : Profile.objects.all()
        }
        return render(request, "profil.html", context)
    return render(request,"403.html")        


def my_info(request,id):
    pats = Patient.objects.all()
    list = []
    for pat in pats:
        list.append(pat.user)
    if request.user in list :        
        patient = get_object_or_404(User, pk=id)
        pat = get_object_or_404(Patient, user = patient)
        context = {
            'usrname': patient.username,
            'first': patient.first_name,
            'last': patient.last_name,
            'naissance' : pat.dateNaissance.date,
            'sexe' : pat.sexe
        }
        return render(request,"my_info.html",context)
    return render(request,"403.html")        

def experts(request,id):
    pats = Patient.objects.all()
    list = []
    for pat in pats:
        list.append(pat.user)
    if request.user in list :         
        user = User.objects.get(id=id)
        pat = Patient.objects.get(user = user)
        experts = a_comme_contact.objects.all().filter(util_connecte = pat)
        all_experts = Expert.objects.all()
        context ={
            'experts': experts,
            'all_experts' : all_experts
        }
        return render(request,"experts.html",context)
    return render(request,"403.html")        

def amis(request,id):
    pats = Patient.objects.all()
    list = []
    for pat in pats:
        list.append(pat.user)
    if request.user in list :        
        user = User.objects.get(id=id)
        pat = Patient.objects.get(user = user)
        amis = a_comme_contact.objects.all().filter(util_connecte = pat)
        all_amis = Patient.objects.all()
        context ={
            'amis': amis,
            'all_amis' : all_amis
        }
        return render(request,"amis.html",context)
    return render(request,"403.html")        

def groupes(request,id):
    pats = Patient.objects.all()
    list = []
    for pat in pats:
        list.append(pat.user)
    if request.user in list :     
        user = User.objects.get(id=id)
        pat = Patient.objects.get(user=user)
        groupes = est_membre_de.objects.filter(pat = pat)
        context={
            'groupes' : groupes
        }
        return render(request,"groupes.html",context)   
    return render(request,"403.html")         

forum/views.py
from accounts.views import logoutUser
from django.contrib.auth.forms import User
from django.db import connection
from django.http.request import HttpRequest
from GlobalApp.models import Expert, publication , room ,Patient , Poste
from accounts.models import Profile
from .models import est_membre_de , a_comme_contact, message
from django.shortcuts import redirect, render
from .forms import *
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def forum_page(request):
    pats = Patient.objects.all()
    exps = Expert.objects.all()
    list = []
    list2 = []
    for pat in pats :
        list.append(pat.user)
    for exp in exps :
        list2.append(exp.user)
    if request.user in list or request.user in list2 :    
        context = {
            'patients' :Patient.objects.all(),
            'experts' : Expert.objects.all(),
            'rooms' : room.objects.all(),
            'postes' : Poste.objects.all(),
            'publications' : publication.objects.all(),
            'est_membre' : est_membre_de.objects.all(),
            'a_contact' : a_comme_contact.objects.all(),
            'profiles' : Profile.objects.all(),
            'relation' : a_comme_contact.objects.all()
        }
        return render(request, "forum.html",context)
    return render(request,"403.html")


#pour lister les amis
@login_required
def forum_page_amis(request,usrname):
    pats = Patient.objects.all()
    exps = Expert.objects.all()
    list = []
    list2 = []
    for pat in pats :
        list.append(pat.user)
    for exp in exps :
        list2.append(exp.user)
    if request.user in list or request.user in list2 :  
        form = messageForm()
        context = {
            'patients' :Patient.objects.all(),
            'experts' : Expert.objects.all(),
            'rooms' : room.objects.all(),
            'messages' : message.objects.all(),
            'contact_selectionne' : User.objects.get(username =usrname),
            'postes' : Poste.objects.all(),
            'publications' : publication.objects.all(),
            'est_membre' : est_membre_de.objects.all(),
            'a_contact' : a_comme_contact.objects.all(),
            'profiles' : Profile.objects.all(),
            'relation' : a_comme_contact.objects.all(),
            'form' : form
        }
        return render(request, "messaging.html",context)
    return render (request,"403.html")    

#pour voir les groupes

@login_required
def forum_page_groupe(request,id):
    pats = Patient.objects.all()
    exps = Expert.objects.all()
    list = []
    list2 = []
    for pat in pats :
        list.append(pat.user)
    for exp in exps :
        list2.append(exp.user)
    if request.user in list or request.user in list2 :  
        context = {
            'patients' :Patient.objects.all(),
            'experts' : Expert.objects.all(),
            'rooms' : room.objects.all(),
            'grp_selectionne' : room.objects.get(pk=id),
            'postes' : Poste.objects.all(),
            'publications' : publication.objects.all(),
            'est_membre' : est_membre_de.objects.all(),
            'a_contact' : a_comme_contact.objects.all(),
            'profiles' : Profile.objects.all(),
            'relation' : a_comme_contact.objects.all()
        }

        return render(request, "forum.html",context)
    return render (request,"403.html")            

#pour publier un message

@login_required
def poste_pub(request, id, pk):
    exps = Expert.objects.all()
    list2 = []
    for exp in exps :
        list2.append(exp.user)
    if  request.user in list2 :  
        groupe = room.objects.get(id=id)
        user = User.objects.get(id=pk)
        the_exp = Expert.objects.get(user = user)
        form = PostForm()

        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                titre = form.cleaned_data['title']
                contenu = form.cleaned_data['body']
                poste = Poste.objects.create(titre=titre, contenu=contenu, publie_par=the_exp)
                poste.save()
                pub = publication.objects.create(publie_dans=groupe, poste_publie=poste)
                pub.save()
        context = {
            'patients' :Patient.objects.all(),
            'experts' : Expert.objects.all(),
            'rooms' : room.objects.all(),
            'grp_selectionne' : room.objects.get(pk=id),
            'postes' : Poste.objects.all(),
            'publications' : publication.objects.all(),
            'est_membre' : est_membre_de.objects.all(),
            'a_contact' : a_comme_contact.objects.all(),
            'profiles' : Profile.objects.all(),
            'relation' : a_comme_contact.objects.all(),
            'form':form
        }
        return render(request, 'forum.html', context)
    return render(request,"403.html")        

#pour envoyer un message

@login_required
def env_message(request, usrname, id):
    pats = Patient.objects.all()
    exps = Expert.objects.all()
    list = []
    list2 = []
    for pat in pats :
        list.append(pat.user)
    for exp in exps :
        list2.append(exp.user)
    if request.user in list  :  
        user = request.user
        de = Patient.objects.get(user=user.id)
        vers = User.objects.get(username=usrname)
        form = messageForm()

        if request.method == 'POST':
            form = messageForm(request.POST)
            if form.is_valid():
                mon_message = form.cleaned_data['message']
                conn = a_comme_contact.objects.get(util_connecte= de,son_contact=vers)
                my_message = message.objects.create(connection = conn , connecte_a_contact =True , msg =  mon_message)
                my_message.save()
        context = {
            'patients' :Patient.objects.all(),
            'experts' : Expert.objects.all(),
            'rooms' : room.objects.all(),
            'messages' : message.objects.all(),
            'contact_selectionne' : User.objects.get(username =usrname),
            'postes' : Poste.objects.all(),
            'publications' : publication.objects.all(),
            'est_membre' : est_membre_de.objects.all(),
            'a_contact' : a_comme_contact.objects.all(),
            'profiles' : Profile.objects.all(),
            'relation' : a_comme_contact.objects.all(),
            'form' : form
        }
        return render(request, 'messaging.html', context)   
    if  request.user in list2 : 
        user = User.objects.get(username=usrname)
        de = Patient.objects.get(user=user)
        vers = User.objects.get(id=id)
        form = messageForm()

        if request.method == 'POST':
            form = messageForm(request.POST)
            if form.is_valid():
                mon_message = form.cleaned_data['message']
                conn = a_comme_contact.objects.get(util_connecte= de,son_contact=vers)
                my_message = message.objects.create(connection = conn , connecte_a_contact =False , msg =  mon_message)
                my_message.save()
        context = {
            'patients' :Patient.objects.all(),
            'experts' : Expert.objects.all(),
            'rooms' : room.objects.all(),
            'messages' : message.objects.all(),
            'contact_selectionne' : User.objects.get(username =usrname),
            'postes' : Poste.objects.all(),
            'publications' : publication.objects.all(),
            'est_membre' : est_membre_de.objects.all(),
            'a_contact' : a_comme_contact.objects.all(),
            'profiles' : Profile.objects.all(),
            'relation' : a_comme_contact.objects.all(),
            'form' : form
        }
        return render(request, 'messaging.html', context)   
    return render(request, "403.html")

quizes/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result

class QuizListView(ListView):
    model = Quiz 
    template_name = 'main.html'

def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quiz.html', {'obj': quiz})

def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

templates/account.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wrong information</title>
</head>
<body>
    <center style="margin-top: 10vh;">
    <h3>Informations entrés non valides .</h3>
    <p><a href="{% url 'home' %}">Revenir à page d'accueil</a></p>
    <p><a href="{% url 'accounts:login' %}">Revernir à page de connexion</a></p>
    </center>
</body>
</html>

templates/experts.html
{% extends 'profil.html' %}

{% block experts %}
	{% for expert in experts %}
        {% for cpt in all_experts %}
            {% if cpt.user.id == expert.son_contact.id %}
	                <p class="des_titres"
	                	style=" color:#f0f8ff; background-image: linear-gradient(to right, #3f98fd, aliceblue); padding-top: 10px; padding-bottom: 10px; padding-left: 25px;">
	                	<a href="{% url 'forum_a' expert.son_contact.username  %}" style="color: white;">
	                		{{expert.son_contact.first_name}} {{expert.son_contact.last_name}} 
	                	</a>
	                </p>
            {% endif %}    
       {% endfor %}    
	{% endfor %}
 {% endblock %}

templates/messaging.html
{% extends 'forum.html' %}
{% load crispy_forms_tags %}
{% block messager %}
<form class="entrer_message" method="POST"  style=" display: grid; grid-gap : 5px; padding: 30px; ">
    {% for a in experts %}
    {% if a.user.id == user.id %}
    <script>
        window.document.getElementById("entrer_message").style.display = 'none'
    </script>
    {% endif %}
    {% endfor %}
    {% csrf_token %}
    {{form.message|as_crispy_field}}
    <center><input
            style="border: 1px solid lightblue; width: 20%; height: 30px; background-color: #87bdd8; color:aliceblue; border-radius: 25px;"
            type="submit" value="envoyer message">
    </center>

</form>

{% endblock %}

templates/profil.html
{% load static %}
<!DOCTYPE html>

<html lang="fr">

<head>
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">

	<title>Forum </title>
	<meta content="" name="description">
	<meta content="" name="keywords">

	<!-- Favicons -->
	<link href="{% static 'assets/img/favicon.png' %}" rel="icon">
	<link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

	<!-- Google Fonts -->
	<link
		href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
		rel="stylesheet">

	<!-- Vendor CSS Files -->
	<link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
	<link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
	<link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">
	<!-- ajouté pour le spostes-->
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<!-- /ajouté pour le spostes-->
	<!------ Include the above in your HEAD tag ---------->

	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css" />

	<!-- Template Main CSS File -->
	<link href="{% static 'assets/css/pg_forum.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
	<style>
		.media-body {
			height: max-content;
			padding: 10px;
			align-content: center;
		}

		#image_container {
			text-align: center;
			padding: 10px;
			border-bottom: 1px solid black;
		}
	</style>
</head>

<body>

	<!-- ======= Top Bar ======= -->
	<div id="topbar" class="d-none d-lg-flex align-items-center fixed-top">
		<div class="container d-flex">
			<div class="contact-info mr-auto">
				<i class="icofont-envelope"></i> <a href="mailto:contact@example.com">contact@example.com</a>
				<i class="icofont-phone"></i>+212 212 121 112
				<i class="icofont-google-map"></i>Route Sidi Bouzid BP 4162 Avenue Mohamed Belkhadir, Safi 46000
			</div>
			<div class="social-links">
				<a href="#" class="twitter"><i class="icofont-twitter"></i></a>
				<a href="#" class="facebook"><i class="icofont-facebook"></i></a>
				<a href="#" class="instagram"><i class="icofont-instagram"></i></a>
				<a href="#" class="skype"><i class="icofont-skype"></i></a>
				<a href="#" class="linkedin"><i class="icofont-linkedin"></i></i></a>
			</div>
		</div>
	</div>
	<!-- ======= Header ======= -->
	<header id="header" class="fixed-top">
		<div class="container d-flex align-items-center">

			<h1 class="logo mr-auto"><a href="{% url 'home' %}">Udoctor</a></h1>
			<!-- Uncomment below if you prefer to use an image logo -->
			<!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

			<nav class="nav-menu d-none d-lg-block">
				<ul>
					<li><a href="{% url 'home' %}" style="margin-right: 40px;">Accueil</a></li>
					{% if request.user.is_authenticated %}
					<li class="active"><a href="{% url 'accounts:profile' %}">Profil</a></li>
					<li><a href="{% url 'forum' %}">forum</a></li>
					<li><a href="{% url 'chat' user.id %}">chatbot</a></li>
					<li><a href="{% url 'AnalyseData' user.id %}">Cheer-up</a></li>
					<li><a href="{% url 'main-view' %}" style="margin-right: 40px;">Quiz</a></li>
					{% endif %}
					<!--<li><a href="#contact">Contactez-nous</a></li>-->

				</ul>
			</nav><!-- .nav-menu -->

			{% if request.user.is_authenticated %}
			<a href="{% url 'accounts:logout' %}" class="appointment-btn scrollto">Logout</a>
			{% else %}
			<a href="{% url 'accounts:login' %}" class="appointment-btn scrollto">login</a>
			{% endif %}



			{% if request.user.is_staff %}
			<a href="{% url 'accounts:register' %}" class="appointment-btn scrollto">Register</a>
			{% else %}

			{% endif %}



		</div>
	</header><!-- End Header -->

	<main id="main">
		
		<!-- ======= Breadcrumbs Section ======= -->
		<section class="breadcrumbs">
			<div class="container">
				<div class="d-flex justify-content-between align-items-center">
					<ol>
						<li><a href="{% url 'home' %}">Accueil</a></li>
						<li>ma page du profil</li>
					</ol>
				</div>

			</div>
		</section><!-- End Breadcrumbs Section -->

		<section class="inner-page" style="background-color:aliceblue;">
			<div class="container">
				<!-- Zone du profil  -->
				<section id="contenaire" class="departments">
					<div class="container">
						
						<div class="row">
							<div class="zone-gauche" style="overflow: auto;">
								<div id="utilisateur-courant" style="text-align: center;">
									<!-- L'image du profile-->
									{% for profil in profiles %}
									a
									{% if profil.user.id == user.id%}
									{{profil.image}}
									<div id="image_container">
										<img src="{{profil.img.url}}" alt="img">
									</div>
									{%endif%}
									{% endfor%}

								</div>
								<div id="choisir">


									<p class="des_titres"
										style=" color:#f0f8ff; background-image: linear-gradient(to right, #3f98fd, aliceblue); padding-top: 10px; padding-bottom: 10px; padding-left: 25px;">
										<a href="{% url 'accounts:my_info' user.id %}" style="color: white;">
											mes informations :
										</a>
									</p>
									<p class="des_titres"
										style=" color:#f0f8ff; background-image: linear-gradient(to right, #3f98fd, aliceblue); padding-top: 10px; padding-bottom: 10px; padding-left: 25px;">
										<a href="{% url 'accounts:amis' user.id %}" style="color: white;">
											mes amis :
										</a>
									</p>

									<p class="des_titres"
										style=" color:#f0f8ff; background-image: linear-gradient(to right, #3f98fd, aliceblue); padding-top: 10px; padding-bottom: 10px; padding-left: 25px;">
										<a href="{% url 'accounts:experts' user.id %}" style="color: white;">
											mes experts :
										</a>
									</p>

									<p class="des_titres"
										style=" color:#f0f8ff; background-image: linear-gradient(to right, #3f98fd, aliceblue); padding-top: 10px; padding-bottom: 10px; padding-left: 25px;">
										<a href="{% url 'accounts:groupes' user.id %}" style="color: white;">
											mes groupes :
										</a>
									</p>
								</div>

							</div>


							<div class="col-lg-9 mt-4 mt-lg-0" style="box-shadow: 10px 10px 10px lightblue;">
								<div class="display_content" id="zone_room">
									{% block my_info %}
									{% endblock %}

									{% block experts %}
									{% endblock %}

									{% block amis %}
									{% endblock %}

									{% block groupes %}
									{% endblock %}
								</div>
							</div>
						</div>

				</section><!-- End Departments Section -->

			</div>
		</section>

	</main><!-- End #main -->


	<div id="preloader"></div>
	<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

	<!-- Vendor JS Files -->
	<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
	<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
	<script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
	<script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
	<script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>

	<!-- Template Main JS File -->
	<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
<script src="{% static 'assets/js/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>score to pass: {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
</div>

<a href="{% url 'main-view' %}" class="btn btn-danger">Retour</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-5">Sauvgarder</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}